version: '3.7'

services:
  keycloak-db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  msc-db:
    image: postgres
    volumes:
    - another_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${ANOTHER_POSTGRES_DB}
      POSTGRES_USER: ${ANOTHER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ANOTHER_POSTGRES_PASSWORD}
    ports:
    - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak
    command: [ "start-dev" ]
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8180:8080"
    restart: unless-stopped
    depends_on:
      - keycloak-db


volumes:
  postgres_data:
    driver: local
  another_postgres_data:
    driver: local
