spring:
  application:
    name: business-management  # Uygulama ismi
  datasource:
    url: jdbc:postgresql://localhost:5433/msc  # PostgreSQL bağlantı URL'si
    username: admin1  # PostgreSQL kullanıcı adı
    password: 123456  # PostgreSQL şifre
    driver-class-name: org.postgresql.Driver  # PostgreSQL JDBC driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      platform: postgres


  liquibase:
    change-log: classpath:/db/changelog/master.yml

server:
  port: 8089  # Uygulama portu

logging:
  level:
    org.hibernate.SQL: DEBUG  # Hibernate SQL sorgularını loglar
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL parametrelerini loglar
