server:
  port: 8085
  servlet:
    context-path: /identity
spring:
  application:
    name:
      identity-server
  security:
    oauth2:
      resourceserver:
        public-paths: /v1/users/user-token
        jwt:
          jwk-set-uri: http://localhost:8180/realms/dev/protocol/openid-connect/certs

# Keycloak Ayarlar?
keycloak:
  auth-server-url: http://localhost:8180
  realm: dev
  resource: ev-csms
  ssl-required: none
  token-uri: http://localhost:8180/realms/dev/protocol/openid-connect/token
  users-uri: http://localhost:8180/admin/realms/dev/users
  client-secret: UomKzxrX1CVQ4ltCknsV9Gd5HWuzLNXK
  client-id: ev-csms
  admin-username: admin
  admin-password: 123456